version: '3.8'

services:
  spotify-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify_data_pipeline

    env_file:
      - .env

    volumes:
      - ./:/app

    stdin_open: true
    tty: true
